version: '3.1'

services:
  phpmyadmin:
    image: phpmyadmin
    ports:
      - ${GUI_PORT}:80
    volumes:
      - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}

      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=${UPLOAD_LIMIT}
